/* =========================================================
   SMART LAND-TO-HOME — application logic
   Single-file app.js: config -> generators -> renderers ->
   calculators -> state -> UI wiring.

   NOTE ON SCOPE (read this before extending):
   This is a static, offline, front-end-only prototype (plain
   HTML/CSS/JS, no server, no database, no paid 3D asset
   library, no live LLM connection). Two consequences:
   1) "3D" views are isometric SVG renders generated by the
      code below, not photoreal Three.js scenes or uploaded
      renders. The math is real and every design is genuinely
      distinct (layout, materials, furniture set) — but it is
      a schematic 3D, not a photoreal one.
   2) The "AI Design Assistant" is a rule-based command
      interpreter (pattern matching -> real state changes),
      not a live call to an LLM, since a static file has no
      backend to hold an API key. The plumbing for wiring a
      real model in is documented at the bottom of this file.
   ========================================================= */

(function(){
"use strict";

/* ---------------------------------------------------------
   0. TINY UTILITIES
--------------------------------------------------------- */
const $  = (sel,root)=> (root||document).querySelector(sel);
const $$ = (sel,root)=> Array.from((root||document).querySelectorAll(sel));
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const round1=v=>Math.round(v*10)/10;
const uid=()=>Math.random().toString(36).slice(2,9);
function mulberry32(seed){
  return function(){
    seed|=0; seed=seed+0x6D2B79F5|0;
    let t=Math.imul(seed^seed>>>15,1|seed);
    t=t+Math.imul(t^t>>>7,61|t)^t;
    return ((t^t>>>14)>>>0)/4294967296;
  };
}
function seededRand(seed){ const r=mulberry32(seed*97+13); return r; }
function toast(msg){
  const t=$('#toast'); t.textContent=msg; t.classList.add('show');
  clearTimeout(toast._h); toast._h=setTimeout(()=>t.classList.remove('show'),2200);
}
function esc(s){return String(s).replace(/&/g,'&amp;').replace(/</g,'&lt;');}

/* ---------------------------------------------------------
   1. GLOBAL CONFIG (admin-editable)
--------------------------------------------------------- */
const CONFIG = {
  minRoomLen: 30,   // ft
  minRoomWid: 20,   // ft   -> 600 sq ft, per spec section 5
  setbackFt: 4,      // uniform setback assumption
  buildableRatio: 0.62, // fraction of (land - setback) usable as footprint
  floorAreaEfficiency: 0.86 // usable-to-gross ratio per floor
};

const WALL_COLORS = [
  {name:'Cloud White', hex:'#F4F1E9'}, {name:'Warm Greige', hex:'#D9CDBB'},
  {name:'Slate Blue', hex:'#7C93AD'}, {name:'Charcoal', hex:'#3B4451'},
  {name:'Sage', hex:'#A9BBA1'}, {name:'Blush', hex:'#E7C9C4'},
  {name:'Navy Accent', hex:'#2C3E63'}, {name:'Terracotta', hex:'#C57B57'},
  {name:'Soft Sand', hex:'#E9DCC3'}, {name:'Deep Olive', hex:'#5B6650'}
];
const FLOOR_MATERIALS = [
  {name:'Matte Ceramic', hex:'#DCD4C6'}, {name:'Oak Wood', hex:'#C79A62'},
  {name:'Italian Marble', hex:'#EDEAE3'}, {name:'Dark Granite', hex:'#4A4E56'},
  {name:'Polished Concrete', hex:'#B9BEC2'}, {name:'Walnut Wood', hex:'#7A5233'},
  {name:'Terrazzo', hex:'#D8CFC1'}, {name:'Slate Stone', hex:'#6C7278'}
];

/* ---------------------------------------------------------
   2. ROOM TYPE CATALOG — every category from Section 16/09
   Each furniture item: key,label,w,d (ft), x,y (fraction of
   room L/D, anchor = center), rot(deg, 0/90/180/270),
   h (ft, for iso height), shape('box'|'oval'|'ring'|'panel'),
   tags: style tags this item appears in ('*' = always).
--------------------------------------------------------- */
const ROOM_TYPES = [
  {key:'living', label:'Living Room', icon:'sofa', furniture:[
    {key:'sofa', label:'Sofa', w:10,d:3.2,h:2.8, x:.52,y:.86, rot:0, tags:['*']},
    {key:'loveseat', label:'Loveseat', w:5,d:3, h:2.6, x:.14,y:.62, rot:90, tags:['modern','family','contemporary','premium']},
    {key:'chair', label:'Armchair', w:3,d:3, h:2.8, x:.90,y:.60, rot:270, tags:['*']},
    {key:'chair2', label:'Armchair', w:3,d:3, h:2.8, x:.90,y:.30, rot:270, tags:['luxury','family','premium']},
    {key:'centerTable', label:'Center Table', w:4.5,d:2.4,h:1.2, x:.52,y:.62, rot:0, shape:'oval', tags:['*']},
    {key:'tvUnit', label:'TV Unit', w:8,d:1.4,h:2, x:.5,y:.08, rot:0, tags:['*']},
    {key:'tv', label:'TV', w:5,d:.3,h:3, x:.5,y:.03, rot:0, shape:'panel', tags:['*']},
    {key:'rug', label:'Rug', w:9,d:6,h:.05, x:.52,y:.68, rot:0, shape:'oval', tags:['minimal','luxury','open','premium','modernlux']}
  ], doors:[{x:.06,y:.5,side:'w'}], windows:[{x:.5,y:0,side:'n',w:8},{x:1,y:.5,side:'e',w:5}]},

  {key:'bathroom', label:'Bathroom', icon:'bath', furniture:[
    {key:'toilet', label:'Toilet', w:2.2,d:2.6,h:1.4, x:.16,y:.85, rot:0, tags:['*']},
    {key:'basin', label:'Wash Basin', w:2.4,d:1.6,h:2.8, x:.16,y:.15, rot:0, tags:['*']},
    {key:'mirror', label:'Mirror', w:2.2,d:.2,h:3, x:.16,y:.03, rot:0, shape:'panel', tags:['*']},
    {key:'shower', label:'Shower', w:3.5,d:3.5,h:2.9, x:.78,y:.22, rot:0, tags:['modern','compact','walkin','wetdry','family','premium','marble']},
    {key:'bathtub', label:'Bathtub', w:5.5,d:2.8,h:1.8, x:.72,y:.75, rot:0, shape:'oval', tags:['luxury','tub','family','premium']},
    {key:'storage', label:'Storage', w:2,d:1.2,h:3, x:.94,y:.5, rot:90, tags:['modern','family','marble','premium','luxury']}
  ], doors:[{x:.02,y:.5,side:'w'}], windows:[{x:.5,y:0,side:'n',w:2.5}]},

  {key:'dining', label:'Dining Room', icon:'dining', furniture:[
    {key:'table', label:'Dining Table', w:8,d:3.6,h:1.3, x:.5,y:.5, rot:0, shape:'oval', tags:['*']},
    {key:'chair1', label:'Chair', w:1.6,d:1.6,h:1.6, x:.5,y:.28, rot:0, tags:['*']},
    {key:'chair2', label:'Chair', w:1.6,d:1.6,h:1.6, x:.5,y:.72, rot:0, tags:['*']},
    {key:'chair3', label:'Chair', w:1.6,d:1.6,h:1.6, x:.24,y:.4, rot:90, tags:['*']},
    {key:'chair4', label:'Chair', w:1.6,d:1.6,h:1.6, x:.24,y:.6, rot:90, tags:['*']},
    {key:'chair5', label:'Chair', w:1.6,d:1.6,h:1.6, x:.76,y:.4, rot:270, tags:['family','large','premium','open']},
    {key:'chair6', label:'Chair', w:1.6,d:1.6,h:1.6, x:.76,y:.6, rot:270, tags:['family','large','premium','open']},
    {key:'sideboard', label:'Sideboard', w:6,d:1.4,h:2.4, x:.5,y:.06, rot:0, tags:['modern','luxury','contemporary','premium']}
  ], doors:[{x:.03,y:.5,side:'w'}], windows:[{x:1,y:.4,side:'e',w:5}]},

  {key:'bedroom', label:'Bedroom', icon:'bed', furniture:[
    {key:'bed', label:'Bed', w:6.5,d:6.5,h:1.6, x:.5,y:.66, rot:0, tags:['*']},
    {key:'side1', label:'Side Table', w:1.8,d:1.6,h:1.6, x:.14,y:.66, rot:0, tags:['*']},
    {key:'side2', label:'Side Table', w:1.8,d:1.6,h:1.6, x:.86,y:.66, rot:0, tags:['*']},
    {key:'wardrobe', label:'Wardrobe', w:8,d:2,h:6.6, x:.5,y:.06, rot:0, tags:['*']},
    {key:'dresser', label:'Dressing Table', w:3.4,d:1.6,h:2.6, x:.9,y:.14, rot:270, tags:['modern','luxury','contemporary','premium','modernlux']},
    {key:'mirror', label:'Mirror', w:1.6,d:.2,h:3, x:.9,y:.03, rot:0, shape:'panel', tags:['modern','luxury','contemporary','premium','modernlux']}
  ], doors:[{x:.04,y:.86,side:'w'}], windows:[{x:.5,y:1,side:'s',w:6}]},

  {key:'masterBedroom', label:'Master Bedroom', icon:'bed', furniture:[
    {key:'kingbed', label:'King Bed', w:7.5,d:7,h:1.7, x:.46,y:.64, rot:0, tags:['*']},
    {key:'side1', label:'Side Table', w:1.8,d:1.6,h:1.6, x:.1,y:.64, rot:0, tags:['*']},
    {key:'side2', label:'Side Table', w:1.8,d:1.6,h:1.6, x:.82,y:.64, rot:0, tags:['*']},
    {key:'wardrobe', label:'Wardrobe', w:9,d:2.1,h:6.8, x:.4,y:.06, rot:0, tags:['*']},
    {key:'dressArea', label:'Dressing Area', w:4,d:2.2,h:2.6, x:.9,y:.16, rot:270, tags:['*']},
    {key:'tv', label:'TV', w:4,d:.3,h:2.6, x:.9,y:.55, rot:270, shape:'panel', tags:['modern','luxury','premium','modernlux','contemporary']},
    {key:'bath', label:'Attached Bath (door)', w:3,d:.3,h:3, x:.05,y:.94, rot:0, shape:'panel', tags:['luxury','premium','family','modernlux']},
    {key:'balconyDoor', label:'Balcony Access', w:4,d:.3,h:3, x:.5,y:1, rot:0, shape:'panel', tags:['open','premium','modernlux','luxury']}
  ], doors:[{x:.02,y:.5,side:'w'}], windows:[{x:.5,y:1,side:'s',w:6}]},

  {key:'kitchen', label:'Kitchen', icon:'kitchen', furniture:[
    {key:'counter', label:'Counter', w:11,d:2, h:3, x:.5,y:.06, rot:0, tags:['*']},
    {key:'sink', label:'Sink', w:2.2,d:1.8,h:3, x:.3,y:.06, rot:0, tags:['*']},
    {key:'stove', label:'Stove', w:2.4,d:1.8,h:3, x:.62,y:.06, rot:0, tags:['*']},
    {key:'oven', label:'Oven', w:2,d:2,h:3.2, x:.86,y:.06, rot:0, tags:['modern','luxury','premium','family','ushape','island']},
    {key:'fridge', label:'Refrigerator', w:2.8,d:2.4,h:6, x:.06,y:.5, rot:90, tags:['*']},
    {key:'cabinet', label:'Cabinet', w:9,d:1.6, h:6.5, x:.5,y:.94, rot:0, tags:['*']},
    {key:'island', label:'Island', w:6,d:3, h:3, x:.5,y:.55, rot:0, tags:['island','modern','luxury','open','smart','premium']},
    {key:'sideCounter', label:'Side Counter', w:2,d:9, h:3, x:.94,y:.5, rot:0, tags:['ushape','parallel','lshape']}
  ], doors:[{x:.03,y:.86,side:'w'}], windows:[{x:.5,y:0,side:'n',w:5}]},

  {key:'drawing', label:'Drawing Room', icon:'sofa', furniture:[
    {key:'sofa', label:'Sofa', w:9,d:3, h:2.8, x:.5,y:.84, rot:0, tags:['*']},
    {key:'chair1', label:'Chair', w:3,d:3, h:2.8, x:.15,y:.5, rot:90, tags:['*']},
    {key:'chair2', label:'Chair', w:3,d:3, h:2.8, x:.85,y:.5, rot:270, tags:['*']},
    {key:'centerTable', label:'Center Table', w:4,d:2.2,h:1.2, x:.5,y:.6, rot:0, shape:'oval', tags:['*']},
    {key:'display', label:'Display/TV', w:6,d:1.2,h:3, x:.5,y:.08, rot:0, tags:['*']}
  ], doors:[{x:.03,y:.5,side:'w'}], windows:[{x:.5,y:0,side:'n',w:7}]},

  {key:'guest', label:'Guest Room', icon:'bed', furniture:[
    {key:'bed', label:'Bed', w:6,d:6,h:1.6, x:.5,y:.68, rot:0, tags:['*']},
    {key:'wardrobe', label:'Wardrobe', w:6,d:2,h:6.5, x:.5,y:.06, rot:0, tags:['*']},
    {key:'chair', label:'Chair', w:2.2,d:2.2,h:2.6, x:.86,y:.7, rot:270, tags:['modern','luxury','premium','family']}
  ], doors:[{x:.04,y:.86,side:'w'}], windows:[{x:.5,y:1,side:'s',w:5}]},

  {key:'family', label:'Family Room', icon:'sofa', furniture:[
    {key:'sofa', label:'Sofa', w:9,d:3, h:2.8, x:.5,y:.84, rot:0, tags:['*']},
    {key:'tv', label:'TV', w:5,d:.3,h:3, x:.5,y:.06, rot:0, shape:'panel', tags:['*']},
    {key:'table', label:'Game/Coffee Table', w:4,d:2.6,h:1.2, x:.5,y:.6, rot:0, tags:['*']},
    {key:'shelf', label:'Shelf Unit', w:5,d:1.2,h:6, x:.9,y:.3, rot:90, tags:['modern','family','premium','luxury']}
  ], doors:[{x:.03,y:.5,side:'w'}], windows:[{x:.5,y:0,side:'n',w:6}]},

  {key:'study', label:'Study Room', icon:'study', furniture:[
    {key:'desk', label:'Desk', w:5,d:2.2,h:2.5, x:.5,y:.14, rot:0, tags:['*']},
    {key:'chair', label:'Chair', w:1.8,d:1.8,h:2.8, x:.5,y:.3, rot:180, tags:['*']},
    {key:'bookshelf', label:'Bookshelf', w:8,d:1.4,h:6.5, x:.5,y:.92, rot:0, tags:['*']},
    {key:'sofa', label:'Reading Chair', w:3,d:3,h:2.8, x:.86,y:.7, rot:270, tags:['luxury','family','premium']}
  ], doors:[{x:.03,y:.5,side:'w'}], windows:[{x:.5,y:0,side:'n',w:5}]},

  {key:'prayer', label:'Prayer Room', icon:'prayer', furniture:[
    {key:'mat', label:'Prayer Mat Area', w:6,d:5,h:.1, x:.5,y:.55, rot:0, shape:'oval', tags:['*']},
    {key:'shelf', label:'Shelf/Altar', w:5,d:1.2,h:3.6, x:.5,y:.08, rot:0, tags:['*']}
  ], doors:[{x:.5,y:1,side:'s'}], windows:[{x:1,y:.4,side:'e',w:3}]},

  {key:'balcony', label:'Balcony', icon:'balcony', furniture:[
    {key:'seat', label:'Seating', w:5,d:2.4,h:2.4, x:.3,y:.7, rot:0, tags:['*']},
    {key:'planter1', label:'Planter', w:2,d:1.4,h:1.6, x:.86,y:.15, rot:0, shape:'oval', tags:['*']},
    {key:'planter2', label:'Planter', w:2,d:1.4,h:1.6, x:.1,y:.15, rot:0, shape:'oval', tags:['modern','luxury','open','premium']},
    {key:'railing', label:'Railing', w:26,d:.4,h:3.2, x:.5,y:.02, rot:0, shape:'panel', tags:['*']}
  ], doors:[{x:.5,y:1,side:'s',w:5}], windows:[]},

  {key:'laundry', label:'Laundry Room', icon:'laundry', furniture:[
    {key:'washer', label:'Washer', w:2.6,d:2.6,h:3, x:.2,y:.16, rot:0, tags:['*']},
    {key:'dryer', label:'Dryer', w:2.6,d:2.6,h:3, x:.46,y:.16, rot:0, tags:['*']},
    {key:'sink', label:'Utility Sink', w:2.2,d:1.8,h:3, x:.75,y:.16, rot:0, tags:['*']},
    {key:'shelf', label:'Shelving', w:9,d:1.4,h:6, x:.5,y:.92, rot:0, tags:['*']}
  ], doors:[{x:.03,y:.5,side:'w'}], windows:[{x:1,y:.5,side:'e',w:3}]},

  {key:'store', label:'Store Room', icon:'store', furniture:[
    {key:'shelfA', label:'Shelving A', w:9,d:1.6,h:7, x:.5,y:.08, rot:0, tags:['*']},
    {key:'shelfB', label:'Shelving B', w:9,d:1.6,h:7, x:.5,y:.92, rot:0, tags:['modern','family','premium']}
  ], doors:[{x:.03,y:.5,side:'w'}], windows:[]},

  {key:'staircase', label:'Staircase', icon:'stairs', furniture:[
    {key:'flight', label:'Stair Flight', w:4,d:16,h:9, x:.24,y:.5, rot:0, tags:['*']},
    {key:'rail', label:'Railing', w:.3,d:16,h:3, x:.4,y:.5, rot:0, shape:'panel', tags:['*']},
    {key:'landing', label:'Landing', w:6,d:4,h:9, x:.75,y:.5, rot:0, tags:['*']}
  ], doors:[{x:.03,y:.5,side:'w'}], windows:[]},

  {key:'garage', label:'Garage / Parking', icon:'garage', furniture:[
    {key:'car1', label:'Car Bay 1', w:8,d:16,h:4.6, x:.28,y:.5, rot:0, tags:['*']},
    {key:'car2', label:'Car Bay 2', w:8,d:16,h:4.6, x:.62,y:.5, rot:0, tags:['modern','family','premium','large']},
    {key:'shelf', label:'Tool Shelving', w:6,d:1.4,h:5, x:.92,y:.1, rot:90, tags:['*']}
  ], doors:[{x:.5,y:1,side:'s',w:12}], windows:[]}
];
const ROOM_BY_KEY = Object.fromEntries(ROOM_TYPES.map(r=>[r.key,r]));

/* ---------------------------------------------------------
   3. STYLE PRESETS — 10 genuinely different treatments.
   Each carries: name, tag (used both for furniture-item
   filtering above AND for the AI assistant / filters),
   wallColor idx, floorMat idx, accent hex, layout variant.
--------------------------------------------------------- */
const STYLE_PRESETS = [
  {name:'Modern',            tag:'modern',      wall:2, floor:0, accent:'#2C3E63', variant:0},
  {name:'Minimal',           tag:'minimal',      wall:0, floor:2, accent:'#3B4451', variant:1},
  {name:'Luxury',            tag:'luxury',       wall:6, floor:2, accent:'#C69749', variant:2},
  {name:'Family / Classic',  tag:'family',       wall:1, floor:1, accent:'#7A5233', variant:3},
  {name:'Open / Airy',       tag:'open',         wall:0, floor:4, accent:'#7C93AD', variant:4},
  {name:'Large Window',      tag:'window',       wall:4, floor:2, accent:'#A9BBA1', variant:1},
  {name:'Contemporary',      tag:'contemporary',  wall:5, floor:3, accent:'#C57B57', variant:2},
  {name:'Space-Saving',      tag:'compact',       wall:1, floor:0, accent:'#5B6650', variant:5},
  {name:'Premium',           tag:'premium',       wall:8, floor:2, accent:'#2C3E63', variant:0},
  {name:'Modern Luxury',     tag:'modernlux',      wall:6, floor:5, accent:'#C69749', variant:2}
];
// per-room-type overrides for the style *names* so labels feel authored
// (matches Sections 9-16 naming) while reusing the same engine + tags.
const NAME_OVERRIDES = {
  bathroom: ['Modern','Minimal','Luxury','Compact','Wet & Dry','Bathtub','Walk-in Shower','Family','Marble','Premium'],
  bathroomTags: ['modern','minimal','luxury','compact','wetdry','tub','walkin','family','marble','premium'],
  kitchen: ['Straight','L-Shaped','U-Shaped','Parallel','Island','Open','Modern','Luxury','Compact','Smart Space-Saving'],
  kitchenTags: ['straight','lshape','ushape','parallel','island','open','modern','luxury','compact','smart'],
  dining: ['Modern','Minimal','Luxury','Family','Open Kitchen','Window Side','Large Family','Contemporary','Space Saving','Premium'],
  bedroom: ['Modern','Minimal','Luxury','Classic','Contemporary','Family','Premium','Space Saving','Window Focused','Modern Luxury']
};

/* ---------------------------------------------------------
   4. LAYOUT TRANSFORM — makes the 10 designs genuinely differ
   in arrangement, not just color. Applies mirroring, a90 clock
   shift and small deterministic jitter per design index.
--------------------------------------------------------- */
function transformFurniture(item, variant, rnd){
  let {x,y,rot}=item;
  if(variant%2===1){ x=1-x; rot=(360-rot)%360; } // mirror horizontally
  if(variant%5===4){ y=1-y; rot=(180-rot+360)%360; } // mirror vertically (space-saving/compact set)
  const jx=(rnd()-.5)*0.05, jy=(rnd()-.5)*0.05;
  x=clamp(x+jx,.04,.96); y=clamp(y+jy,.04,.96);
  return {x,y,rot};
}

/* ---------------------------------------------------------
   5. DESIGN GENERATOR — builds the 10 designs for a room type.
   Deterministic (seeded) so reloading gives the same catalog;
   admin-added custom designs are appended separately.
--------------------------------------------------------- */
const catalogCache = {};
function generateDesigns(typeKey){
  if(catalogCache[typeKey]) return catalogCache[typeKey];
  const rt = ROOM_BY_KEY[typeKey];
  const names = NAME_OVERRIDES[typeKey] || STYLE_PRESETS.map(p=>p.name);
  const tags  = NAME_OVERRIDES[typeKey+'Tags'] || STYLE_PRESETS.map(p=>p.tag);
  const list=[];
  for(let i=0;i<10;i++){
    const preset = STYLE_PRESETS[i];
    const rnd = seededRand(i+1 + typeKey.length*13);
    const tag = tags[i];
    const furniture = rt.furniture
      .filter(f=> f.tags.includes('*') || f.tags.includes(tag))
      .map(f=>{
        const t = transformFurniture(f, preset.variant, rnd);
        return Object.assign({}, f, t);
      });
    list.push({
      id: typeKey+'-'+i,
      roomType: typeKey,
      roomLabel: rt.label,
      index: i,
      name: (names[i]||preset.name)+' '+rt.label,
      style: tag,
      styleName: names[i]||preset.name,
      length: CONFIG.minRoomLen,
      width: CONFIG.minRoomWid,
      wallColor: WALL_COLORS[preset.wall].hex,
      wallColorName: WALL_COLORS[preset.wall].name,
      floorMaterial: FLOOR_MATERIALS[preset.floor].name,
      floorColor: FLOOR_MATERIALS[preset.floor].hex,
      accent: preset.accent,
      furniture,
      doors: rt.doors,
      windows: rt.windows,
      custom:false
    });
  }
  catalogCache[typeKey]=list;
  return list;
}
function allDesignsFor(typeKey){
  const base = generateDesigns(typeKey);
  const custom = STATE.customDesigns.filter(d=>d.roomType===typeKey);
  return base.concat(custom);
}
function findDesign(id){
  for(const rt of ROOM_TYPES){
    const d = allDesignsFor(rt.key).find(x=>x.id===id);
    if(d) return d;
  }
  return null;
}

/* ---------------------------------------------------------
   6. APPLICATION STATE
--------------------------------------------------------- */
const STATE = {
  land:null,            // raw land input
  calc:null,             // computed area/floors/rooms
  chosenPlanIdx:null,     // 0/1/2 -> Plan A/B/C
  rooms:[],               // [{id, type, label, floor, length, width, area, designId, overrides:{...}}]
  floors:[],              // ['Ground','1st',...]
  customDesigns:[],       // admin-added designs, same shape as generated ones
  projects: JSON.parse(localStorage.getItem('sl2h_projects')||'[]'),
  activeProjectId:null,
  compareSet:[],          // up to 3 design ids
  aiLog:[],
  lighting:'day'
};
try{ STATE.customDesigns = JSON.parse(localStorage.getItem('sl2h_custom_designs')||'[]'); }catch(e){}
try{ const c = JSON.parse(localStorage.getItem('sl2h_config')||'null'); if(c) Object.assign(CONFIG,c); }catch(e){}

/* ---------------------------------------------------------
   7. LAND & FLOOR & ROOM CALCULATION ENGINE
--------------------------------------------------------- */
function computeLand(input){
  const totalArea = input.length*input.width;
  const setback = CONFIG.setbackFt;
  const netL = Math.max(input.length-2*setback,4);
  const netW = Math.max(input.width-2*setback,4);
  const setbackArea = totalArea - netL*netW;
  const buildableArea = round1(netL*netW*CONFIG.buildableRatio);
  const footprint = round1(Math.min(buildableArea, netL*netW));
  const openSpace = round1(totalArea-footprint);
  const suggestedFloorArea = round1(footprint*CONFIG.floorAreaEfficiency);
  return {totalArea:round1(totalArea), buildableArea, setbackArea:round1(setbackArea), footprint, openSpace, suggestedFloorArea, netL, netW};
}

function suggestFloorPlans(input, calc){
  const roomWanted = ['bedrooms','bathrooms','livingRoom','diningRoom','kitchen','drawingRoom','guestRoom','studyRoom']
    .reduce((s,k)=> s+(Number(input[k])||0), 0);
  const perFloorCapacity = Math.max(1, Math.floor(calc.suggestedFloorArea/(CONFIG.minRoomLen*CONFIG.minRoomWid)));
  const minFloorsNeeded = Math.max(1, Math.ceil(roomWanted/Math.max(perFloorCapacity,1)));
  const plans=[
    {id:'A', name:'Ground Floor', floors:1, desc:'Single-storey — fastest to build, best for smaller families or where fewer floors are preferred.'},
    {id:'B', name:'Ground + 1st Floor', floors:2, desc:'Balanced footprint and headroom — the common choice for the requirements you entered.'},
    {id:'C', name:'Ground + 1st + 2nd Floor', floors:3, desc:'Maximises room count on a smaller footprint, at higher construction cost.'}
  ];
  plans.forEach(p=>{
    p.roomsPerFloor = Math.ceil(roomWanted/p.floors);
    p.fits = p.floors>=Math.min(minFloorsNeeded,3);
    p.recommended = p.floors===clamp(minFloorsNeeded,1,3);
  });
  return {plans, minFloorsNeeded, roomWanted, perFloorCapacity};
}

const FLOOR_NAMES=['Ground','1st Floor','2nd Floor','3rd Floor'];
function buildRoomList(input, floors){
  const wanted = [
    ['bedrooms','bedroom','Bedroom'], ['bathrooms','bathroom','Bathroom'],
    ['livingRoom','living','Living Room'], ['diningRoom','dining','Dining Room'],
    ['kitchen','kitchen','Kitchen'], ['drawingRoom','drawing','Drawing Room'],
    ['guestRoom','guest','Guest Room'], ['studyRoom','study','Study Room'],
    ['balcony','balcony','Balcony'], ['parking','garage','Garage / Parking']
  ];
  const rooms=[];
  wanted.forEach(([field,typeKey,label])=>{
    let n=Number(input[field])||0;
    if(field==='bedrooms' && n>0){ // first bedroom becomes a Master Bedroom automatically
      rooms.push(mkRoom('masterBedroom','Master Bedroom'));
      n-=1;
    }
    for(let i=0;i<n;i++) rooms.push(mkRoom(typeKey, n>1? `${label} ${i+1}`:label));
  });
  // always include a staircase if more than one floor
  if(floors>1) rooms.push(mkRoom('staircase','Staircase'));
  // family-size aware extras
  if(Number(input.familySize)>5 && !wanted.some(([f])=>input[f])) rooms.push(mkRoom('family','Family Room'));
  // assign to floors round-robin, keeping ground floor priority for kitchen/living/parking/guest
  const groundFirst=['kitchen','living','drawing','dining','guest','garage','staircase'];
  let gi=0, oi=0;
  const perFloor = Math.max(1,Math.ceil(rooms.length/floors));
  const groundRooms = rooms.filter(r=>groundFirst.includes(r.type));
  const upperRooms = rooms.filter(r=>!groundFirst.includes(r.type));
  const assigned=[];
  groundRooms.forEach(r=>{ r.floor=0; assigned.push(r); });
  let f=floors>1?1:0, count=0;
  upperRooms.forEach(r=>{
    r.floor = floors>1 ? (1+ (count % (floors-1))) : 0;
    count++; assigned.push(r);
  });
  // if ground floor overloaded and upper floors exist, rebalance a little
  return assigned;
}
function mkRoom(typeKey,label){
  return {id:uid(), type:typeKey, label, length:CONFIG.minRoomLen, width:CONFIG.minRoomWid,
    area:CONFIG.minRoomLen*CONFIG.minRoomWid, floor:0, designId:null, overrides:{}};
}

/* ---------------------------------------------------------
   8. 2D SVG FLOOR-PLAN RENDERER
--------------------------------------------------------- */
function svgOpen(vb){ return `<svg viewBox="0 0 ${vb} ${vb*0.68}" xmlns="http://www.w3.org/2000/svg">`; }
function shapeEl(shape,x,y,w,h,fill,stroke,rot){
  const cx=x+w/2, cy=y+h/2;
  const tr = rot? ` transform="rotate(${rot} ${cx} ${cy})"`:'';
  if(shape==='oval') return `<ellipse cx="${cx}" cy="${cy}" rx="${w/2}" ry="${h/2}" fill="${fill}" stroke="${stroke}" stroke-width="1"${tr}/>`;
  if(shape==='panel') return `<rect x="${x}" y="${y}" width="${w}" height="${h}" fill="${fill}" stroke="${stroke}" stroke-width="1" rx="1"${tr}/>`;
  return `<rect x="${x}" y="${y}" width="${w}" height="${h}" rx="3" fill="${fill}" stroke="${stroke}" stroke-width="1.2"${tr}/>`;
}
function render2D(design, opts){
  opts=opts||{};
  const L=design.length, W=design.width;
  const pad=3, scale=(90-pad*2)/Math.max(L,W)* (Math.max(L,W)<=30?1:30/Math.max(L,W));
  const S = 2.4; // px per ft baseline, viewbox 0..(L*S+40)
  const vbW = L*S+56, vbH = W*S+56;
  const ox=32, oy=28;
  let s = `<svg viewBox="0 0 ${vbW} ${vbH}" xmlns="http://www.w3.org/2000/svg" font-family="JetBrains Mono, monospace">`;
  s += `<rect x="0" y="0" width="${vbW}" height="${vbH}" fill="#fff"/>`;
  // floor fill
  s += `<rect x="${ox}" y="${oy}" width="${L*S}" height="${W*S}" fill="${design.floorColor}"/>`;
  // subtle floor pattern
  for(let i=1;i<L;i+=2){ s+=`<line x1="${ox+i*S}" y1="${oy}" x2="${ox+i*S}" y2="${oy+W*S}" stroke="#00000008" stroke-width="1"/>`; }
  // walls
  s += `<rect x="${ox-3}" y="${oy-3}" width="${L*S+6}" height="${W*S+6}" fill="none" stroke="${design.wallColor}" stroke-width="6"/>`;
  s += `<rect x="${ox}" y="${oy}" width="${L*S}" height="${W*S}" fill="none" stroke="#16202E" stroke-width="1.4"/>`;
  // furniture
  (design.furniture||[]).forEach(f=>{
    const fw=f.w*S, fh=f.d*S;
    const fx = ox + f.x*L*S - fw/2, fy = oy + f.y*W*S - fh/2;
    s += shapeEl(f.shape||'box', fx, fy, fw, fh, '#fff', design.accent, f.rot);
    s += `<text x="${fx+fw/2}" y="${fy+fh/2+3}" font-size="7" text-anchor="middle" fill="#16202E">${esc(f.label)}</text>`;
  });
  // doors (arc)
  (design.doors||[]).forEach(d=>{
    const dx=ox+d.x*L*S, dy=oy+d.y*W*S;
    s += `<circle cx="${dx}" cy="${dy}" r="3" fill="#C1554B"/>`;
    s += `<text x="${dx}" y="${dy-6}" font-size="6.5" text-anchor="middle" fill="#C1554B">DOOR</text>`;
  });
  (design.windows||[]).forEach(w=>{
    const wx=ox+w.x*L*S, wy=oy+w.y*W*S;
    s += `<circle cx="${wx}" cy="${wy}" r="3" fill="#3E6E78"/>`;
    s += `<text x="${wx}" y="${wy-6}" font-size="6.5" text-anchor="middle" fill="#3E6E78">WIN</text>`;
  });
  // dimension text
  s += `<text x="${ox+L*S/2}" y="${oy+W*S+18}" font-size="9" text-anchor="middle" fill="#48586E">${L}′ × ${W}′  •  ${Math.round(L*W)} sq ft</text>`;
  s += `<text x="${ox}" y="16" font-size="9" fill="#16202E" font-weight="700">${esc(design.name)}</text>`;
  s += `</svg>`;
  return s;
}

/* ---------------------------------------------------------
   9. ISOMETRIC "3D" SVG RENDERER
--------------------------------------------------------- */
const ISO = { a: Math.cos(Math.PI/6), b: Math.sin(Math.PI/6) };
function isoPt(x,y,z, ox,oy, k){
  // x: along length(ft), y: along width(ft), z: height(ft)
  const px = ox + (x-y)*ISO.a*k;
  const py = oy + (x+y)*ISO.b*k - z*k;
  return [px,py];
}
function shade(hex, amt){
  const c=hex.replace('#','');
  const num=parseInt(c,16);
  let r=(num>>16)+amt, g=((num>>8)&0xff)+amt, b=(num&0xff)+amt;
  r=clamp(r,0,255); g=clamp(g,0,255); b=clamp(b,0,255);
  return '#'+[r,g,b].map(v=>v.toString(16).padStart(2,'0')).join('');
}
function isoBoxPath(x,y,z,w,d,h, ox,oy,k){
  const p = (X,Y,Z)=>isoPt(X,Y,Z,ox,oy,k);
  const top   = [p(x,y,z+h), p(x+w,y,z+h), p(x+w,y+d,z+h), p(x,y+d,z+h)];
  const front = [p(x,y+d,0), p(x+w,y+d,0), p(x+w,y+d,z+h), p(x,y+d,z+h)];
  const right = [p(x+w,y,0), p(x+w,y+d,0), p(x+w,y+d,z+h), p(x+w,y,z+h)];
  const poly = pts=>pts.map(pt=>pt.join(',')).join(' ');
  return {top:poly(top), front:poly(front), right:poly(right), labelAt:p(x+w/2,y+d/2,z+h)};
}
function render3D(design, opts){
  opts=opts||{};
  const lighting = opts.lighting||'day';
  const tint = lighting==='night' ? -70 : lighting==='evening' ? -28 : 0;
  const bg = lighting==='night' ? '#0B1D3A' : lighting==='evening' ? '#F3E3CF' : '#F2EFE7';
  const L=design.length, W=design.width;
  const k = 210/(L+W);
  const ox = 40, oy = 60 + W*ISO.b*k;
  let s = `<svg viewBox="0 0 ${(L+W)*ISO.a*k+80} ${(L+W)*ISO.b*k+ (opts.wallH||9)*k + 90}" xmlns="http://www.w3.org/2000/svg" font-family="JetBrains Mono, monospace">`;
  s += `<rect x="0" y="0" width="100%" height="100%" fill="${bg}"/>`;
  // floor
  const fp=[isoPt(0,0,0,ox,oy,k),isoPt(L,0,0,ox,oy,k),isoPt(L,W,0,ox,oy,k),isoPt(0,W,0,ox,oy,k)];
  s += `<polygon points="${fp.map(p=>p.join(',')).join(' ')}" fill="${shade(design.floorColor,tint)}" stroke="#00000022"/>`;
  // back walls (left wall along y at x=0, back wall along x at y=0)
  const wallH=opts.wallH||9;
  const wL=[isoPt(0,0,0,ox,oy,k),isoPt(0,W,0,ox,oy,k),isoPt(0,W,wallH,ox,oy,k),isoPt(0,0,wallH,ox,oy,k)];
  const wB=[isoPt(0,0,0,ox,oy,k),isoPt(L,0,0,ox,oy,k),isoPt(L,0,wallH,ox,oy,k),isoPt(0,0,wallH,ox,oy,k)];
  s += `<polygon points="${wL.map(p=>p.join(',')).join(' ')}" fill="${shade(design.wallColor,tint-14)}" stroke="#00000022"/>`;
  s += `<polygon points="${wB.map(p=>p.join(',')).join(' ')}" fill="${shade(design.wallColor,tint)}" stroke="#00000022"/>`;
  // furniture, painter's-sort back-to-front
  const items=(design.furniture||[]).slice().sort((a,b)=> (a.x+a.y)-(b.x+b.y));
  items.forEach(f=>{
    const fw=f.w, fd=f.d, fh=Math.min(f.h||2.5, wallH-.3);
    let x=f.x*L-fw/2, y=f.y*W-fd/2;
    x=clamp(x,0,L-fw); y=clamp(y,0,W-fd);
    const box=isoBoxPath(x,y,0,fw,fd,fh,ox,oy,k);
    const base = design.accent;
    s += `<polygon points="${box.top}" fill="${shade(base,tint+26)}" stroke="#00000030" stroke-width=".6"/>`;
    s += `<polygon points="${box.front}" fill="${shade(base,tint-8)}" stroke="#00000030" stroke-width=".6"/>`;
    s += `<polygon points="${box.right}" fill="${shade(base,tint-38)}" stroke="#00000030" stroke-width=".6"/>`;
    if(!opts.hideLabels){
      s += `<text x="${box.labelAt[0]}" y="${box.labelAt[1]-4}" font-size="6.4" text-anchor="middle" fill="#16202E">${esc(f.label)}</text>`;
    }
  });
  if(lighting==='night'){
    items.forEach(f=>{
      if(['tv','lamp','pendant'].some(k2=>f.key.includes(k2))){
        const c=isoPt(f.x*L,f.y*W,(f.h||2)+.3,ox,oy,k);
        s+=`<circle cx="${c[0]}" cy="${c[1]}" r="10" fill="#FFD98A55"/>`;
      }
    });
    const c=isoPt(L*.5,W*.5,wallH-.2,ox,oy,k);
    s+=`<circle cx="${c[0]}" cy="${c[1]}" r="16" fill="#FFE7A855"/>`;
  }
  s += `<text x="16" y="18" font-size="9" fill="${lighting==='night'?'#F7F4EC':'#16202E'}" font-weight="700">${esc(design.name)}</text>`;
  s += `<text x="16" y="30" font-size="7.5" fill="${lighting==='night'?'#86D6DE':'#48586E'}">${esc(design.floorMaterial)} floor • ${esc(design.wallColorName)} walls • ${lighting} view</text>`;
  s += `</svg>`;
  return s;
}


/* ---------------------------------------------------------
   10. NAVIGATION
--------------------------------------------------------- */
function goSection(id){
  $$('.view').forEach(v=>v.classList.add('hidden'));
  const el = document.getElementById(id);
  if(el) el.classList.remove('hidden');
  $$('.navlinks button').forEach(b=>b.classList.toggle('active', b.dataset.go===id));
  window.scrollTo({top:0,behavior:'smooth'});
  $('.navlinks').classList.remove('open');
  if(id==='view-library') renderLibraryTabs();
  if(id==='view-dashboard') renderDashboard();
  if(id==='view-house'){ renderCompleteHouse(); renderLandView(); }
  if(id==='view-admin') renderAdmin();
}
function wireNav(){
  $$('.navlinks button, [data-go]').forEach(b=>{
    b.addEventListener('click', ()=> goSection(b.dataset.go));
  });
  $('#hamb').addEventListener('click', ()=> $('.navlinks').classList.toggle('open'));
}

/* ---------------------------------------------------------
   11. HERO — blueprint/render reveal slider
--------------------------------------------------------- */
function wireHero(){
  const range = $('#revealRange');
  const layer = $('#renderLayer');
  range.addEventListener('input', ()=>{
    layer.style.setProperty('--reveal', (100-range.value)+'%');
  });
}

/* ---------------------------------------------------------
   12. LAND INPUT FORM -> CALCULATION -> FLOOR PLAN CHOICE
--------------------------------------------------------- */
function readLandForm(){
  const f = $('#landForm');
  const num = n=>Number(f.querySelector(`[name=${n}]`).value)||0;
  const val = n=>f.querySelector(`[name=${n}]`).value;
  let length=num('length'), width=num('width');
  if(val('unit')==='m'){ length*=3.281; width*=3.281; }
  return {
    length, width, unit:val('unit'), roadSide:val('roadSide'), frontSide:val('frontSide'),
    familySize:num('familySize'), floorsWanted:num('floorsWanted'),
    bedrooms:num('bedrooms'), bathrooms:num('bathrooms'), livingRoom:num('livingRoom'),
    diningRoom:num('diningRoom'), kitchen:num('kitchen'), drawingRoom:num('drawingRoom'),
    guestRoom:num('guestRoom'), studyRoom:num('studyRoom'), balcony:num('balcony'),
    parking:num('parking'), other: f.querySelector('[name=other]').value
  };
}
function onCalculate(e){
  e.preventDefault();
  const input = readLandForm();
  if(input.length<10 || input.width<10){ toast('Please enter realistic land length & width.'); return; }
  STATE.land = input;
  STATE.calc = computeLand(input);
  const {plans} = suggestFloorPlans(input, STATE.calc);
  STATE.floorPlans = plans;
  renderLandResults();
  $('#floorPlanBlock').classList.remove('hidden');
  $('#floorPlanBlock').scrollIntoView({behavior:'smooth', block:'start'});
}
function renderLandResults(){
  const c = STATE.calc;
  $('#resultStrip').innerHTML = `
    <div class="result-cell"><b>${c.totalArea.toLocaleString()}</b><span>Total Land (sq ft)</span></div>
    <div class="result-cell"><b>${c.buildableArea.toLocaleString()}</b><span>Buildable Area</span></div>
    <div class="result-cell"><b>${c.setbackArea.toLocaleString()}</b><span>Setback Area</span></div>
    <div class="result-cell"><b>${c.footprint.toLocaleString()}</b><span>Building Footprint</span></div>
    <div class="result-cell"><b>${c.suggestedFloorArea.toLocaleString()}</b><span>Suggested Floor Area</span></div>`;
  $('#resultStrip').closest('.panel').classList.remove('hidden');
  renderFloorPlanOptions();
}
function renderFloorPlanOptions(){
  const wrap=$('#planOptions'); wrap.innerHTML='';
  STATE.floorPlans.forEach((p,idx)=>{
    const div=document.createElement('div');
    div.className='plan-opt'+(STATE.chosenPlanIdx===idx?' sel':'');
    div.innerHTML = `<span class="eyebrow">Plan ${p.id}${p.recommended?' • Recommended':''}</span>
      <h4>${p.name}</h4>
      <div class="stack">${Array.from({length:p.floors}).map(()=>'<div class="flr"></div>').join('')}</div>
      <p>${p.desc}</p>
      <p class="mono" style="margin-top:8px;color:#48586E">~${p.roomsPerFloor} rooms / floor</p>`;
    div.addEventListener('click', ()=> choosePlan(idx));
    wrap.appendChild(div);
  });
}
function choosePlan(idx){
  STATE.chosenPlanIdx = idx;
  const plan = STATE.floorPlans[idx];
  STATE.floors = FLOOR_NAMES.slice(0,plan.floors);
  STATE.rooms = buildRoomList(STATE.land, plan.floors);
  renderFloorPlanOptions();
  renderRoomSchedulePreview();
  $('#roomScheduleBlock').classList.remove('hidden');
  $('#roomScheduleBlock').scrollIntoView({behavior:'smooth',block:'start'});
  toast(`Plan ${plan.id} selected — ${STATE.rooms.length} rooms recommended.`);
}
function renderRoomSchedulePreview(){
  const wrap=$('#roomListPreview'); wrap.innerHTML='';
  STATE.rooms.forEach(r=>{
    const rt = ROOM_BY_KEY[r.type];
    const row=document.createElement('div'); row.className='room-row';
    row.innerHTML = `<b>${esc(r.label)}</b>
      <span class="tag">${r.length}′ × ${r.width}′</span>
      <span class="tag">${r.area} sq ft</span>
      <span class="tag">${STATE.floors[r.floor]||'Ground'}</span>
      <span class="tag">${r.designId? findDesign(r.designId).name : 'No design selected'}</span>
      <button class="btn btn-line btn-sm" data-pick="${r.id}">Choose Design</button>`;
    row.querySelector('[data-pick]').addEventListener('click', ()=>{
      goSection('view-library'); selectLibraryTab(rt.key); pendingRoomPick=r.id;
      toast(`Pick a ${rt.label} design for "${r.label}"`);
    });
    wrap.appendChild(row);
  });
  $('#notice-min-room').textContent = `The prototype uses a configurable minimum room size of ${CONFIG.minRoomLen} × ${CONFIG.minRoomWid} ft (${CONFIG.minRoomLen*CONFIG.minRoomWid} sq ft). Actual room dimensions, setbacks and construction requirements must be verified according to applicable building regulations and by a qualified architect or engineer.`;
}
let pendingRoomPick=null;

/* ---------------------------------------------------------
   13. DASHBOARD
--------------------------------------------------------- */
function renderDashboard(){
  const has = !!STATE.calc;
  $('#dashEmpty').classList.toggle('hidden', has);
  $('#dashFull').classList.toggle('hidden', !has);
  if(has){
    const selected = STATE.rooms.filter(r=>r.designId).length;
    $('#dashGrid').innerHTML = `
      <div class="dash-card"><b>${STATE.calc.totalArea.toLocaleString()}</b><span>Land Area (sq ft)</span></div>
      <div class="dash-card"><b>${STATE.floors.length}</b><span>Suggested Floors</span></div>
      <div class="dash-card"><b>${STATE.rooms.length}</b><span>Total Rooms</span></div>
      <div class="dash-card"><b>${selected}</b><span>Selected Designs</span></div>
      <div class="dash-card"><b>${STATE.projects.length}</b><span>Saved Projects</span></div>`;
  }
  renderProjectsList();
}
function renderProjectsList(){
  const wrap=$('#projectsList'); wrap.innerHTML='';
  if(!STATE.projects.length){ wrap.innerHTML='<p class="field-note">No saved projects yet — save your current plan below.</p>'; return; }
  STATE.projects.forEach(p=>{
    const row=document.createElement('div'); row.className='proj-row';
    row.innerHTML = `<b>${esc(p.name)}</b><span class="meta">${p.rooms.length} rooms • ${p.calc?p.calc.totalArea.toLocaleString():'?'} sq ft</span>
      <button class="btn btn-line btn-sm" data-load="${p.id}">Continue</button>
      <button class="btn btn-line btn-sm" data-dup="${p.id}">Duplicate</button>
      <button class="btn btn-danger btn-sm" data-del="${p.id}">Delete</button>`;
    row.querySelector('[data-load]').onclick=()=>loadProject(p.id);
    row.querySelector('[data-dup]').onclick=()=>duplicateProject(p.id);
    row.querySelector('[data-del]').onclick=()=>deleteProject(p.id);
    wrap.appendChild(row);
  });
}
function persistProjects(){ localStorage.setItem('sl2h_projects', JSON.stringify(STATE.projects)); }
function saveProject(){
  if(!STATE.calc){ toast('Enter land details and pick a floor plan first.'); return; }
  const name = prompt('Project name?', STATE.activeName || ('My Plot '+new Date().toLocaleDateString()));
  if(!name) return;
  const data = {id: STATE.activeProjectId||uid(), name, land:STATE.land, calc:STATE.calc,
    chosenPlanIdx:STATE.chosenPlanIdx, floors:STATE.floors, rooms:STATE.rooms, savedAt:Date.now()};
  const i = STATE.projects.findIndex(p=>p.id===data.id);
  if(i>-1) STATE.projects[i]=data; else STATE.projects.push(data);
  STATE.activeProjectId=data.id; STATE.activeName=name;
  persistProjects(); renderDashboard(); toast('Project saved.');
}
function loadProject(id){
  const p = STATE.projects.find(x=>x.id===id); if(!p) return;
  STATE.land=p.land; STATE.calc=p.calc; STATE.chosenPlanIdx=p.chosenPlanIdx;
  STATE.floors=p.floors; STATE.rooms=p.rooms; STATE.activeProjectId=p.id; STATE.activeName=p.name;
  goSection('view-house'); toast(`Loaded "${p.name}".`);
}
function duplicateProject(id){
  const p = STATE.projects.find(x=>x.id===id); if(!p) return;
  const copy = JSON.parse(JSON.stringify(p)); copy.id=uid(); copy.name=p.name+' (copy)';
  STATE.projects.push(copy); persistProjects(); renderDashboard(); toast('Duplicated.');
}
function deleteProject(id){
  if(!confirm('Delete this project? This cannot be undone.')) return;
  STATE.projects = STATE.projects.filter(x=>x.id!==id); persistProjects(); renderDashboard();
}

/* ---------------------------------------------------------
   14. DESIGN LIBRARY
--------------------------------------------------------- */
let libTab = 'living';
let libFilters = {style:'', size:''};
function renderLibraryTabs(){
  const tabs=$('#libTabs'); tabs.innerHTML='';
  ROOM_TYPES.forEach(rt=>{
    const b=document.createElement('button'); b.className='lib-tab'+(rt.key===libTab?' active':'');
    b.textContent=rt.label; b.onclick=()=>selectLibraryTab(rt.key);
    tabs.appendChild(b);
  });
  renderLibraryGrid();
}
function selectLibraryTab(key){ libTab=key; renderLibraryTabs(); }
function renderLibraryGrid(){
  const grid=$('#designGrid'); grid.innerHTML='';
  let list = allDesignsFor(libTab);
  if(libFilters.style) list = list.filter(d=>d.style===libFilters.style);
  if(libFilters.size==='small') list = list.filter(d=>d.length*d.width<500);
  if(libFilters.size==='large') list = list.filter(d=>d.length*d.width>700);
  $('#libCount').textContent = `${list.length} designs`;
  const styleSel = $('#filterStyle');
  const uniq = Array.from(new Set(generateDesigns(libTab).map(d=>d.style)));
  styleSel.innerHTML = '<option value="">All styles</option>'+uniq.map(s=>`<option value="${s}">${esc(generateDesigns(libTab).find(d=>d.style===s).styleName)}</option>`).join('');
  styleSel.value = libFilters.style;

  list.forEach(d=>{
    const card=document.createElement('div'); card.className='design-card'; card.dataset.view='2d';
    card.innerHTML = `
      <label class="compare-check"><input type="checkbox" data-cmp="${d.id}" ${STATE.compareSet.includes(d.id)?'checked':''}/></label>
      <div class="view-toggle"><button data-v="2d" class="active">2D</button><button data-v="3d">3D</button></div>
      <div class="thumb">${render2D(d)}</div>
      <div class="body">
        <span class="style-pill">${esc(d.styleName)}</span>
        <h4>${esc(d.name)}</h4>
        <div class="meta-row"><span>${d.length}′ × ${d.width}′</span><span>${d.length*d.width} sq ft</span></div>
        <div class="btnrow">
          <button class="btn btn-line" data-open="${d.id}">View</button>
          <button class="btn btn-brass" data-select="${d.id}">Select</button>
        </div>
      </div>`;
    card.querySelectorAll('.view-toggle button').forEach(btn=>{
      btn.addEventListener('click',()=>{
        card.querySelectorAll('.view-toggle button').forEach(x=>x.classList.remove('active'));
        btn.classList.add('active');
        card.querySelector('.thumb').innerHTML = btn.dataset.v==='2d'? render2D(d): render3D(d,{lighting:STATE.lighting});
      });
    });
    card.querySelector('[data-open]').onclick=()=>openDesignModal(d.id);
    card.querySelector('[data-select]').onclick=()=>assignDesignToPendingRoom(d.id);
    card.querySelector('[data-cmp]').addEventListener('change',(e)=>toggleCompare(d.id,e.target.checked));
    grid.appendChild(card);
  });
}
function assignDesignToPendingRoom(designId){
  if(!pendingRoomPick){
    // no target room in flow — just open the customizer
    openDesignModal(designId); return;
  }
  const room = STATE.rooms.find(r=>r.id===pendingRoomPick);
  if(room){ room.designId = designId; toast('Design assigned to '+room.label+'.'); }
  pendingRoomPick=null;
  goSection('view-house');
}
function toggleCompare(id,checked){
  if(checked){ if(STATE.compareSet.length>=3){ toast('You can compare up to 3 designs.'); renderLibraryGrid(); return;} STATE.compareSet.push(id); }
  else STATE.compareSet = STATE.compareSet.filter(x=>x!==id);
  renderCompareBar();
}
function renderCompareBar(){
  let bar=$('#compareBar');
  if(!STATE.compareSet.length){ bar.classList.add('hidden'); return; }
  bar.classList.remove('hidden');
  bar.querySelector('b').textContent = `${STATE.compareSet.length} design(s) selected for comparison`;
}
function openCompare(){
  if(STATE.compareSet.length<2){ toast('Select at least 2 designs to compare.'); return; }
  const grid=$('#compareGrid'); grid.innerHTML='';
  STATE.compareSet.forEach(id=>{
    const d=findDesign(id); if(!d) return;
    const col=document.createElement('div'); col.className='compare-col';
    col.innerHTML = `${render2D(d)}<h4 style="margin-top:10px;font-size:14px">${esc(d.name)}</h4>
      <table>
        <tr><td>Style</td><td>${esc(d.styleName)}</td></tr>
        <tr><td>Size</td><td>${d.length}′ × ${d.width}′</td></tr>
        <tr><td>Area</td><td>${d.length*d.width} sq ft</td></tr>
        <tr><td>Furniture</td><td>${d.furniture.length} items</td></tr>
        <tr><td>Wall</td><td>${esc(d.wallColorName)}</td></tr>
        <tr><td>Floor</td><td>${esc(d.floorMaterial)}</td></tr>
        <tr><td>Windows</td><td>${d.windows.length}</td></tr>
        <tr><td>Doors</td><td>${d.doors.length}</td></tr>
      </table>`;
    grid.appendChild(col);
  });
  $('#compareModal').classList.remove('hidden');
}

/* ---------------------------------------------------------
   15. DESIGN MODAL — view / customize
--------------------------------------------------------- */
let modalDesign=null, modalView='2d', modalLighting='day';
function openDesignModal(id){
  modalDesign = JSON.parse(JSON.stringify(findDesign(id)));
  modalDesign._sourceId = id;
  modalView='2d'; modalLighting='day';
  $('#designModal').classList.remove('hidden');
  renderModal();
}
function closeModal(){ $('#designModal').classList.add('hidden'); }
function renderModal(){
  const d=modalDesign;
  $('#modalTitle').textContent = d.name;
  $('#modalCanvas').innerHTML = modalView==='2d'? render2D(d) : render3D(d,{lighting:modalLighting});
  $$('.stage-toggle button').forEach(b=>b.classList.toggle('active', b.dataset.v===modalView));
  $('#lightingRow').classList.toggle('hidden', modalView!=='3d');
  $$('.lighting-row button').forEach(b=>b.classList.toggle('active', b.dataset.light===modalLighting));

  // wall swatches
  $('#wallSwatches').innerHTML = WALL_COLORS.map(c=>`<span class="swatch ${c.hex===d.wallColor?'sel':''}" style="background:${c.hex}" data-wall="${c.hex}" title="${c.name}"></span>`).join('');
  $('#floorSwatches').innerHTML = FLOOR_MATERIALS.map(c=>`<span class="swatch ${c.hex===d.floorColor?'sel':''}" style="background:${c.hex}" data-floor="${c.hex}" data-floorname="${c.name}" title="${c.name}"></span>`).join('');
  $$('#wallSwatches .swatch').forEach(sw=>sw.onclick=()=>{ d.wallColor=sw.dataset.wall; renderModal(); });
  $$('#floorSwatches .swatch').forEach(sw=>sw.onclick=()=>{ d.floorColor=sw.dataset.floor; d.floorMaterial=sw.dataset.floorname; renderModal(); });

  // size sliders
  $('#lenRange').value=d.length; $('#lenVal').textContent=d.length+'′';
  $('#widRange').value=d.width; $('#widVal').textContent=d.width+'′';
  $('#modalArea').textContent = (d.length*d.width)+' sq ft';

  // furniture list
  $('#furnList').innerHTML = d.furniture.map((f,i)=>`
    <div class="furn-row">
      <input type="checkbox" data-fi="${i}" ${f._hidden?'':'checked'}/>
      <span>${esc(f.label)}</span><small>${f.w}′×${f.d}′</small>
    </div>`).join('');
  $$('#furnList input').forEach(cb=>cb.onchange=()=>{
    const i=Number(cb.dataset.fi); d.furniture[i]._hidden = !cb.checked;
    d.furniture = d.furniture.filter(f=>true); // keep, filter on render
    renderModalCanvasOnly();
  });
  $('#legend').innerHTML = `<span>${d.doors.length} door(s)</span><span>${d.windows.length} window(s)</span><span>${d.furniture.length} labeled objects</span>`;
}
function renderModalCanvasOnly(){
  const visible = Object.assign({}, modalDesign, {furniture: modalDesign.furniture.filter(f=>!f._hidden)});
  $('#modalCanvas').innerHTML = modalView==='2d'? render2D(visible) : render3D(visible,{lighting:modalLighting});
  $('#modalArea').textContent = (modalDesign.length*modalDesign.width)+' sq ft';
}
function wireModal(){
  $$('.stage-toggle button').forEach(b=>b.onclick=()=>{ modalView=b.dataset.v; renderModal(); });
  $$('.lighting-row button').forEach(b=>b.onclick=()=>{ modalLighting=b.dataset.light; renderModal(); });
  $('#lenRange').addEventListener('input', e=>{ modalDesign.length=Number(e.target.value); $('#lenVal').textContent=e.target.value+'′'; renderModalCanvasOnly(); validateRoomFit(); });
  $('#widRange').addEventListener('input', e=>{ modalDesign.width=Number(e.target.value); $('#widVal').textContent=e.target.value+'′'; renderModalCanvasOnly(); validateRoomFit(); });
  $('#modalClose').onclick=closeModal;
  $('#designModal').addEventListener('click', e=>{ if(e.target.id==='designModal') closeModal(); });
  $('#modalSaveDesign').onclick=()=>{
    // persist as a customization on the design (session-level) and, if a room slot is open, assign it
    if(pendingRoomPick){
      const room = STATE.rooms.find(r=>r.id===pendingRoomPick);
      if(room){ room.designId = modalDesign._sourceId; room.overrides = {
        wallColor:modalDesign.wallColor, floorColor:modalDesign.floorColor, floorMaterial:modalDesign.floorMaterial,
        length:modalDesign.length, width:modalDesign.width, hidden: modalDesign.furniture.filter(f=>f._hidden).map(f=>f.key)
      }; room.length=modalDesign.length; room.width=modalDesign.width; room.area=modalDesign.length*modalDesign.width; }
      pendingRoomPick=null;
      toast('Customized design assigned.'); closeModal(); goSection('view-house');
    } else {
      toast('Customization kept for this session. Pick a room slot in "My Land" to assign it.');
    }
  };
}
function validateRoomFit(){
  const d=modalDesign; const area=d.length*d.width;
  const box = $('#fitNotice');
  if(area < 80){ box.className='notice danger'; box.textContent='This room is too small to fit its furniture set comfortably. Please increase the size.'; box.classList.remove('hidden'); }
  else { box.classList.add('hidden'); }
}

/* ---------------------------------------------------------
   16. COMPLETE HOUSE BUILDER
--------------------------------------------------------- */
let houseFloorIdx=0, exploded=false;
function renderCompleteHouse(){
  const has = STATE.rooms && STATE.rooms.length;
  $('#houseEmpty').classList.toggle('hidden', !!has);
  $('#houseFull').classList.toggle('hidden', !has);
  if(!has) return;
  renderFloorTabs();
  renderAssignGrid();
  renderHouseCanvas();
  renderSchedule();
}
function renderFloorTabs(){
  const wrap=$('#floorTabs'); wrap.innerHTML='';
  STATE.floors.forEach((f,i)=>{
    const b=document.createElement('button'); b.className='floor-tab'+(i===houseFloorIdx?' active':'');
    b.textContent=f; b.onclick=()=>{ houseFloorIdx=i; renderCompleteHouse(); };
    wrap.appendChild(b);
  });
}
function renderAssignGrid(){
  const wrap=$('#assignGrid'); wrap.innerHTML='';
  const roomsHere = STATE.rooms.filter(r=>r.floor===houseFloorIdx);
  if(!roomsHere.length){ wrap.innerHTML='<p class="field-note">No rooms on this floor.</p>'; return; }
  roomsHere.forEach(r=>{
    const rt = ROOM_BY_KEY[r.type];
    const opts = allDesignsFor(r.type);
    const card=document.createElement('div'); card.className='assign-card';
    card.innerHTML = `<label>${esc(r.label)} — ${r.length}′×${r.width}′ (${r.area} sq ft)</label>
      <select>${opts.map(o=>`<option value="${o.id}" ${o.id===r.designId?'selected':''}>${esc(o.name)}</option>`).join('')}</select>`;
    card.querySelector('select').addEventListener('change', e=>{ r.designId=e.target.value; renderHouseCanvas(); renderSchedule(); });
    wrap.appendChild(card);
  });
}
function renderHouseCanvas(){
  const wrap=$('#houseCanvas');
  const floors = exploded ? STATE.floors : [STATE.floors[houseFloorIdx]];
  let s = `<svg viewBox="0 0 900 ${exploded? 260*STATE.floors.length+40 : 320}" xmlns="http://www.w3.org/2000/svg" font-family="JetBrains Mono, monospace">`;
  STATE.floors.forEach((fname,fi)=>{
    if(!exploded && fi!==houseFloorIdx) return;
    const yOff = exploded ? fi*260+10 : 10;
    const roomsHere = STATE.rooms.filter(r=>r.floor===fi);
    const cols=Math.max(1,Math.ceil(Math.sqrt(roomsHere.length)));
    let x=20,y=yOff+22,rowH=0,colCount=0;
    const maxW=860;
    s+=`<text x="20" y="${yOff+12}" font-size="12" fill="#16202E" font-weight="700">${fname}</text>`;
    roomsHere.forEach(r=>{
      const w=Math.max(70, r.length*3), h=Math.max(50, r.width*3);
      if(x+w>maxW){ x=20; y+=rowH+14; rowH=0; }
      const design = r.designId? findDesign(r.designId): null;
      const fill = design? design.floorColor : '#EDE8DB';
      const stroke = design? design.wallColor : '#B9BEC2';
      s+=`<rect x="${x}" y="${y}" width="${w}" height="${h}" fill="${fill}" stroke="${stroke}" stroke-width="3"/>`;
      s+=`<text x="${x+6}" y="${y+14}" font-size="8.5" fill="#16202E">${esc(r.label)}</text>`;
      s+=`<text x="${x+6}" y="${y+h-6}" font-size="7" fill="#48586E">${r.length}′×${r.width}′</text>`;
      x+=w+14; rowH=Math.max(rowH,h);
    });
  });
  s+=`</svg>`;
  wrap.innerHTML=s;
}
function renderSchedule(){
  const tb=$('#scheduleBody'); tb.innerHTML='';
  STATE.rooms.forEach(r=>{
    const design = r.designId? findDesign(r.designId): null;
    tb.innerHTML += `<tr><td>${esc(r.label)}</td><td class="num">${r.length} ft</td><td class="num">${r.width} ft</td>
      <td class="num">${r.area} sq ft</td><td>${STATE.floors[r.floor]||'Ground'}</td><td>${design? esc(design.name):'<span style="color:#C1554B">Not selected</span>'}</td></tr>`;
  });
  // validation: footprint vs sum of ground-floor rooms
  const groundArea = STATE.rooms.filter(r=>r.floor===0).reduce((s,r)=>s+r.area,0);
  const box=$('#houseValidation');
  if(STATE.calc && groundArea > STATE.calc.suggestedFloorArea*1.05){
    box.className='notice danger';
    box.textContent = `Ground-floor rooms total ${groundArea.toLocaleString()} sq ft, which exceeds the suggested floor area of ${STATE.calc.suggestedFloorArea.toLocaleString()} sq ft. Reduce room sizes or move rooms to another floor.`;
  } else if(STATE.calc){
    box.className='notice ok';
    box.textContent = `Ground-floor rooms fit within the suggested floor area (${groundArea.toLocaleString()} of ${STATE.calc.suggestedFloorArea.toLocaleString()} sq ft used).`;
  }
}
function wireHouse(){
  $('#expToggle').addEventListener('change', e=>{ exploded=e.target.checked; renderHouseCanvas(); });
}

/* ---------------------------------------------------------
   17. LAND + HOUSE VIEW
--------------------------------------------------------- */
function renderLandView(){
  const wrap=$('#landViewCanvas');
  if(!STATE.land){ wrap.innerHTML='<p class="field-note">Enter your land details on the "My Land" page first.</p>'; return; }
  const L=STATE.land.length, W=STATE.land.width;
  const S = 480/Math.max(L,W);
  const ox=20, oy=20;
  const setback=CONFIG.setbackFt;
  const footW=(L-2*setback)*0.86, footD=(W-2*setback)*0.86;
  let s=`<svg viewBox="0 0 ${L*S+40} ${W*S+40}" xmlns="http://www.w3.org/2000/svg" font-family="JetBrains Mono, monospace">`;
  s+=`<rect x="0" y="0" width="100%" height="100%" fill="#EAF3EE"/>`;
  s+=`<rect x="${ox}" y="${oy}" width="${L*S}" height="${W*S}" fill="none" stroke="#4F9D69" stroke-width="3" stroke-dasharray="6 4"/>`;
  s+=`<text x="${ox}" y="${oy-6}" font-size="10" fill="#245e39">Land Boundary — ${L}′ × ${W}′</text>`;
  const fx=ox+(L*S-footW*S)/2, fy=oy+(W*S-footD*S)/2;
  s+=`<rect x="${fx}" y="${fy}" width="${footW*S}" height="${footD*S}" fill="#D9CDBB" stroke="#16202E" stroke-width="2"/>`;
  s+=`<text x="${fx+6}" y="${fy+16}" font-size="9" fill="#16202E">House Footprint</text>`;
  s+=`<rect x="${ox+8}" y="${fy+footD*S+8}" width="${footW*S*0.4}" height="${(oy+W*S-8)-(fy+footD*S+8)}" fill="#C7D9C9" stroke="#4F9D69"/>`;
  s+=`<text x="${ox+12}" y="${fy+footD*S+22}" font-size="8" fill="#245e39">Garden</text>`;
  s+=`<rect x="${ox+footW*S*0.5}" y="${fy+footD*S+8}" width="${footW*S*0.45}" height="${(oy+W*S-8)-(fy+footD*S+8)}" fill="#DADFE2" stroke="#6C7278"/>`;
  s+=`<text x="${ox+footW*S*0.5+6}" y="${fy+footD*S+22}" font-size="8" fill="#3B4451">Parking</text>`;
  s+=`<rect x="${ox+L*S/2-14}" y="${oy+W*S-2}" width="28" height="6" fill="#3B4451"/>`;
  s+=`<text x="${ox+L*S/2}" y="${oy+W*S+16}" font-size="8" text-anchor="middle" fill="#3B4451">Gate / Entrance</text>`;
  s+=`</svg>`;
  wrap.innerHTML=s;
}

/* ---------------------------------------------------------
   18. ADMIN PANEL
--------------------------------------------------------- */
let adminTab='settings';
function renderAdmin(){
  $$('.admin-tab').forEach(b=>b.classList.toggle('active', b.dataset.tab===adminTab));
  $$('.admin-pane').forEach(p=>p.classList.toggle('hidden', p.id!=='admin-'+adminTab));
  if(adminTab==='settings'){
    $('#admMinLen').value=CONFIG.minRoomLen; $('#admMinWid').value=CONFIG.minRoomWid;
  }
  if(adminTab==='designs'){
    const sel=$('#admRoomType'); sel.innerHTML = ROOM_TYPES.map(rt=>`<option value="${rt.key}">${rt.label}</option>`).join('');
    renderAdminDesignList();
  }
}
function renderAdminDesignList(){
  const wrap=$('#admDesignList'); wrap.innerHTML='';
  if(!STATE.customDesigns.length){ wrap.innerHTML='<p class="field-note">No custom designs added yet.</p>'; return; }
  STATE.customDesigns.forEach(d=>{
    const row=document.createElement('div'); row.className='kv-row';
    row.innerHTML=`<span>${esc(d.name)} <span class="mono" style="color:#48586E">(${ROOM_BY_KEY[d.roomType].label})</span></span>
      <button class="btn btn-danger btn-sm" data-del="${d.id}">Delete</button>`;
    row.querySelector('button').onclick=()=>{
      STATE.customDesigns = STATE.customDesigns.filter(x=>x.id!==d.id);
      localStorage.setItem('sl2h_custom_designs', JSON.stringify(STATE.customDesigns));
      renderAdminDesignList(); toast('Design removed.');
    };
    wrap.appendChild(row);
  });
}
function wireAdmin(){
  $$('.admin-tab').forEach(b=>b.onclick=()=>{ adminTab=b.dataset.tab; renderAdmin(); });
  $('#admSaveSettings').onclick=()=>{
    CONFIG.minRoomLen = Number($('#admMinLen').value)||30;
    CONFIG.minRoomWid = Number($('#admMinWid').value)||20;
    localStorage.setItem('sl2h_config', JSON.stringify(CONFIG));
    for(const k in catalogCache) delete catalogCache[k];
    toast('Minimum room size updated to '+CONFIG.minRoomLen+'×'+CONFIG.minRoomWid+' ft. New designs will use it.');
  };
  $('#admAddDesign').onclick=()=>{
    const typeKey=$('#admRoomType').value;
    const name=$('#admDesignName').value.trim() || 'Custom Design';
    const styleTag=$('#admStyleTag').value.trim() || 'custom';
    const wall = $('#admWallColor').value || '#F4F1E9';
    const floor = $('#admFloorColor').value || '#DCD4C6';
    const rt = ROOM_BY_KEY[typeKey];
    const rnd = seededRand(STATE.customDesigns.length+7);
    const furniture = rt.furniture.map(f=> Object.assign({}, f, transformFurniture(f, STATE.customDesigns.length%6, rnd)));
    const d = {id:'custom-'+uid(), roomType:typeKey, roomLabel:rt.label, name, style:styleTag, styleName:name,
      length:CONFIG.minRoomLen, width:CONFIG.minRoomWid, wallColor:wall, wallColorName:'Custom',
      floorMaterial:'Custom', floorColor:floor, accent:'#2C3E63', furniture, doors:rt.doors, windows:rt.windows, custom:true};
    STATE.customDesigns.push(d);
    localStorage.setItem('sl2h_custom_designs', JSON.stringify(STATE.customDesigns));
    renderAdminDesignList(); toast('Custom design added to the '+rt.label+' library.');
  };
}

/* ---------------------------------------------------------
   19. EXPORT
--------------------------------------------------------- */
function exportPDF(){ window.print(); }
function exportPNG(){
  const svg = $('#houseCanvas svg') || $('#modalCanvas svg');
  if(!svg){ toast('Open a plan or design first.'); return; }
  const xml = new XMLSerializer().serializeToString(svg);
  const svg64 = btoa(unescape(encodeURIComponent(xml)));
  const img = new Image();
  img.onload = ()=>{
    const canvas=document.createElement('canvas');
    const vb = svg.viewBox.baseVal;
    canvas.width = (vb.width||900)*2; canvas.height=(vb.height||500)*2;
    const ctx=canvas.getContext('2d');
    ctx.fillStyle='#fff'; ctx.fillRect(0,0,canvas.width,canvas.height);
    ctx.drawImage(img,0,0,canvas.width,canvas.height);
    const a=document.createElement('a'); a.download='smart-land-to-home.png'; a.href=canvas.toDataURL('image/png'); a.click();
  };
  img.src='data:image/svg+xml;base64,'+svg64;
}

/* ---------------------------------------------------------
   20. AI DESIGN ASSISTANT (rule-based command interpreter)
--------------------------------------------------------- */
function aiRespond(text){
  const t=text.toLowerCase();
  let reply=null;
  const styleWords = {modern:'modern', luxury:'luxury', minimal:'minimal', premium:'premium', compact:'compact',
    contemporary:'contemporary', family:'family', open:'open', airy:'open', large:'family'};
  const roomWords = Object.fromEntries(ROOM_TYPES.map(r=>[r.label.toLowerCase(),r.key]).concat(
    [['bathroom','bathroom'],['living room','living'],['bedroom','bedroom'],['master bedroom','masterBedroom'],
     ['kitchen','kitchen'],['dining','dining'],['dining table','dining']]));

  // "give me a <style> <room>" / "make my <room> more <style>"
  let matchedRoom=null;
  for(const label in roomWords){ if(t.includes(label)){ matchedRoom=roomWords[label]; break; } }
  let matchedStyle=null;
  for(const w in styleWords){ if(t.includes(w)){ matchedStyle=styleWords[w]; break; } }

  if(matchedRoom && /add another|add a|add /.test(t) && t.includes('bedroom')){
    STATE.rooms.push(mkRoom('bedroom', 'Bedroom '+(STATE.rooms.filter(r=>r.type==='bedroom').length+2)));
    reply = `Added another bedroom to your plan — ${STATE.rooms.length} rooms total now. Open "Complete House" to assign it a design.`;
  } else if(matchedRoom && matchedStyle){
    const options = allDesignsFor(matchedRoom).filter(d=>d.style===matchedStyle || d.styleName.toLowerCase().includes(matchedStyle));
    const pick = options[0] || allDesignsFor(matchedRoom)[0];
    const room = STATE.rooms.find(r=>r.type===matchedRoom);
    if(room){ room.designId = pick.id; reply = `Done — set "${room.label}" to ${pick.name}. Check it in Complete House.`; }
    else { reply = `I found "${pick.name}" in the ${ROOM_BY_KEY[matchedRoom].label} library — open the Design Library to select it, since you don't have that room in your current plan yet.`; }
  } else if(matchedRoom && /larger|bigger|increase/.test(t)){
    const room = STATE.rooms.find(r=>r.type===matchedRoom);
    if(room){ room.length=Math.round(room.length*1.15); room.width=Math.round(room.width*1.15); room.area=room.length*room.width;
      reply = `Enlarged "${room.label}" to ${room.length}′ × ${room.width}′ (${room.area} sq ft).`; }
    else reply = `You don't have a ${ROOM_BY_KEY[matchedRoom].label} in the current plan yet.`;
  } else if(/wall color|change the wall|paint/.test(t)){
    reply = `Open any design's card → View → the wall-color swatches in the customize panel to repaint it — I've highlighted the Design Library for you.`;
  } else if(matchedRoom){
    reply = `Here's the ${ROOM_BY_KEY[matchedRoom].label} library — 10 designs, each with a 2D and 3D view.`;
  } else {
    reply = `I can switch a room's design by style ("make my living room more modern"), add rooms ("add another bedroom"), or resize a room ("make the kitchen larger"). Try one of those, or browse the Design Library directly.`;
  }
  renderSchedule && STATE.rooms.length && renderCompleteHouse();
  return reply;
}
function wireAI(){
  const fab=$('#aiFab'), panel=$('#aiPanel');
  fab.onclick=()=> panel.classList.toggle('open');
  const send=()=>{
    const inp=$('#aiInput'); const text=inp.value.trim(); if(!text) return;
    logAI('user', text); inp.value='';
    setTimeout(()=> logAI('bot', aiRespond(text)), 260);
  };
  $('#aiSendBtn').onclick=send;
  $('#aiInput').addEventListener('keydown', e=>{ if(e.key==='Enter') send(); });
  $$('.ai-suggest button').forEach(b=> b.onclick=()=>{ $('#aiInput').value=b.textContent; send(); });
  logAI('bot','Hi — I can adjust designs, resize rooms, or add rooms to your plan. Try “make my living room more modern”.');
}
function logAI(who,text){
  STATE.aiLog.push({who,text});
  const log=$('#aiLog');
  const div=document.createElement('div'); div.className='ai-msg '+who; div.textContent=text;
  log.appendChild(div); log.scrollTop=log.scrollHeight;
}

/* ---------------------------------------------------------
   21. WIRE-UP & BOOT
--------------------------------------------------------- */
function wireMisc(){
  $('#landForm').addEventListener('submit', onCalculate);
  $('#saveProjectBtn').addEventListener('click', saveProject);
  $('#exportPdfBtn').addEventListener('click', exportPDF);
  $('#exportPngBtn').addEventListener('click', exportPNG);
  $('#filterStyle').addEventListener('change', e=>{ libFilters.style=e.target.value; renderLibraryGrid(); });
  $('#filterSize').addEventListener('change', e=>{ libFilters.size=e.target.value; renderLibraryGrid(); });
  $('#compareOpenBtn').addEventListener('click', openCompare);
  $('#compareClose').addEventListener('click', ()=> $('#compareModal').classList.add('hidden'));
  $('#compareModal').addEventListener('click', e=>{ if(e.target.id==='compareModal') $('#compareModal').classList.add('hidden'); });
  $$('.cat-card').forEach(c=> c.addEventListener('click', ()=>{ goSection('view-library'); selectLibraryTab(c.dataset.room); }));
}
document.addEventListener('DOMContentLoaded', ()=>{
  wireNav(); wireHero(); wireModal(); wireHouse(); wireAdmin(); wireAI(); wireMisc();
  goSection('view-home');
});

/* ---------------------------------------------------------
   WIRING A REAL LLM (optional, for developers extending this):
   Replace aiRespond() with a fetch() to your own backend that
   proxies POST https://api.anthropic.com/v1/messages — never
   put a real API key in this client-side file. See Anthropic's
   docs at https://docs.claude.com for request/response shapes.
--------------------------------------------------------- */

window.SL2H = { CONFIG, STATE, ROOM_TYPES, ROOM_BY_KEY, generateDesigns, allDesignsFor, findDesign,
  render2D, render3D, computeLand, suggestFloorPlans };
})();